format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
unstable_features = true
wrap_comments = true
