unstable_features = true
wrap_comments = true
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
